apiVersion: v1
kind: Service
metadata:
  name: dogfinder-frontend-service
  labels:
    app: dogfinder
    tier: frontend
spec:
  type: LoadBalancer 
  ports:
  - port: 80 
    targetPort: 80 
    protocol: TCP
  selector:
    app: dogfinder
    tier: frontend
